C tricks - Part 1
dev-knights/dev-knights.github.io pull request #1
Opened 2018-01-30 04:36 UTC by arandilopez

2018-01-30 17:31 UTC, rejonpardenilla requested changes
En general me gustó mucho el artículo, explicas muy bien algo que daba mucho miedo aprender en primer semestre. Sólo marqué algunos typos para corregir. Ya quiero leer la segunda parte 👍

2018-01-30 17:31 UTC, rejonpardenilla commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +> Un apuntador es un variable que posee un tipo de dato, él cuál *apunta* a una dirección de memoria.
"una variable", variable es femenino

2018-01-30 17:31 UTC, rejonpardenilla commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +El resultado del código sería los siguiente
"el siguiente"

2018-01-30 17:31 UTC, rejonpardenilla commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +Si, el apuntador `a_numero` es una referencia a `numero`, asi que cualquier operacion que hagamos sobre `*a_numero` sera sobre el valor de `numero`. La reasignacion, por ejemplo, de `*a_numero` hará
"será"

2018-01-30 17:31 UTC, rejonpardenilla commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +Espero que encuentres útil ésta información. En la siguiente publicación de esta serie hablaré sobre los `struct` en C y cómo hacer nuestros propios tipos de datos complejos para dar a neustros progr
"nuestros"

2018-01-30 18:12 UTC, arandilopez commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +> Un apuntador es un variable que posee un tipo de dato, él cuál *apunta* a una dirección de memoria.
fixed

2018-01-30 18:12 UTC, arandilopez commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +El resultado del código sería los siguiente
Listo

2018-01-30 18:12 UTC, arandilopez commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +Si, el apuntador `a_numero` es una referencia a `numero`, asi que cualquier operacion que hagamos sobre `*a_numero` sera sobre el valor de `numero`. La reasignacion, por ejemplo, de `*a_numero` hará
listo

2018-01-30 18:12 UTC, arandilopez commented on _posts/2018-01-29-tips-en-c-parte-1.markdown
> +Espero que encuentres útil ésta información. En la siguiente publicación de esta serie hablaré sobre los `struct` en C y cómo hacer nuestros propios tipos de datos complejos para dar a neustros progr
listo

2018-01-31 17:35 UTC, rejonpardenilla approved these changes

2018-01-31 17:51 UTC, merged